// src/app/models/order.ts

export type OrderStatus = 'Confirmed' | 'Packed' | 'Shipped' | 'Delivered';

export interface OrderItem {
  productId: string;
  name: string;
  image: string;
  quantity: number;
  color: string;
  size: string;
  material: string;
  price: number; // price for this item (per unit with customization)
}

export interface LogisticsInfo {
  carrier: string;
  trackingId: string;
  currentLocation: string;
}

export interface Order {
  id?: number;                 // generated by json-server
  userId: number;              // id of the customer (from /users)
  placedOn: string;            // e.g. "03/12/2025"
  amount: number;              // total amount
  status: OrderStatus;         // Confirmed / Packed / Shipped / Delivered
  items: OrderItem[];          // all cart items in this order
  estimatedDelivery: string;   // e.g. "10/12/2025"
  logistics: LogisticsInfo;    // tracking information
}
